### ISSUE TITLE
display IRC output (responses, errors) in Jenkins log for debugging

### ISSUE THREAD

**Issue by jywarren** [publiclab/plotsbot#117]
@ryzokuken @icarito is this possible?

**Comment by jywarren** [comment]
Such as how many people plotsbot has quieted and if it worked?

**Comment by ryzokuken** [comment]
I haven't used said Jenkins instance yet. Are we using it for CI? That actually determines if we can display output on it or not (but it's most probably yes, no matter what).

**Comment by jywarren** [comment]
Actually we're running plotsbot in a container managed in Jenkins, at
https://jenkins.laboratoriopublico.org. Could we configure a log location
to dump this stuff into, which we could then read via Jenkins interface?

**Comment by icarito** [comment]
I've just added:
```
sleep 10
docker-compose logs
```
to the jenkins job for plotsbot. Hopefully this will make it easier to figure out its status.

**Comment by icarito** [comment]
Otherwise we could redirect stdout to a file and then the log would be accessible from https://jenkins.laboratoriopublico.org/job/Plotsbot/ws/

**Comment by icarito** [comment]
https://jenkins.laboratoriopublico.org/job/Plotsbot/lastSuccessfulBuild/console shows the output log now:
```
+ docker-compose logs
Attaching to plotsbot_plotsbot_1
[36mplotsbot_1  |[0m yarn run v1.2.1
[36mplotsbot_1  |[0m $ node .
[36mplotsbot_1  |[0m Plotsbot is listening on port 4000!
[36mplotsbot_1  |[0m logging in with plotsbot
[36mplotsbot_1  |[0m /usr/src/app/node_modules/irc/lib/irc.js:849
[36mplotsbot_1  |[0m                         throw err;
[36mplotsbot_1  |[0m                         ^
[36mplotsbot_1  |[0m 
[36mplotsbot_1  |[0m TypeError: Cannot read property 'send' of undefined
[36mplotsbot_1  |[0m     at quietAction (/usr/src/app/src/behaviors/quiet.js:9:14)
[36mplotsbot_1  |[0m     at MemoryBehavior.newAction [as action] (/usr/src/app/src/models/memory-behavior.js:13:16)
[36mplotsbot_1  |[0m     at joinBehaviors.forEach.behavior (/usr/src/app/src/behaviors/index.js:61:51)
[36mplotsbot_1  |[0m     at Array.forEach (<anonymous>)
[36mplotsbot_1  |[0m     at client.addJoinHandler (/usr/src/app/src/behaviors/index.js:60:26)
[36mplotsbot_1  |[0m     at Client.client.addListener (/usr/src/app/src/interfaces/irc.js:13:7)
[36mplotsbot_1  |[0m     at emitThree (events.js:136:13)
[36mplotsbot_1  |[0m     at Client.emit (events.js:217:7)
[36mplotsbot_1  |[0m     at Client.<anonymous> (/usr/src/app/node_modules/irc/lib/irc.js:495:22)
[36mplotsbot_1  |[0m     at emitOne (events.js:116:13)
[36mplotsbot_1  |[0m error Command failed with exit code 1.
[36mplotsbot_1  |[0m info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
